// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // @ts-expect-error - directUrl is supported by Prisma CLI in v7 but might be missing from TypeScript types in this release
    directUrl: process.env["DIRECT_URL"],
  },
});
